In [1]:
#numpy arrays
#to store multiple data in a array
#collection of homogenous data
#numpy arrays are much faster than list,tuple,dictionary or set

In [2]:
#how to create a numpy array

In [3]:
import numpy as np

In [6]:
var = np.array([1,2,3,4,5])

In [7]:
type(var)

numpy.ndarray

In [9]:
print(var)

[1 2 3 4 5]


In [10]:
np.array([1,2,3,4,5],dtype=float)

array([1., 2., 3., 4., 5.])

In [11]:
np.array([1,2,3,4,5],dtype=str)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [12]:
#access the element of a numpy array

In [13]:
var

array([1, 2, 3, 4, 5])

In [14]:
var[0]

1

In [15]:
var[1]

2

In [16]:
for i in range(0,len(var)):
    print(var[i])

1
2
3
4
5


In [17]:
for i in var:
    print(i)

1
2
3
4
5


In [18]:
#multidimensional

In [20]:
var1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
var1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
var1.shape

(3, 3)

In [24]:
var[1:4]

array([2, 3, 4])

In [26]:
var1[1,1:3]

array([5, 6])

In [28]:
var1[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [29]:
#functions/methods in numpy

In [31]:
var2 = np.array([1,2,3,4,5,6,7,8,9])

In [33]:
var2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
var3 = np.array([1,2,3,4,5,6,7,8])

In [36]:
var3.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
var3.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [41]:
#numpy of size 50 and all the elements are 0
var4 = np.zeros(5,dtype=int)
var4

array([0, 0, 0, 0, 0])

In [42]:
var4 = np.zeros((3,3),dtype=int)
var4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [43]:
#numpy of size 50 and all the elements are 1
var5 = np.ones((3,3),dtype=int)
var5

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [44]:
np.full(5,10,dtype=int)

array([10, 10, 10, 10, 10])

In [45]:
np.full((5,5),10,dtype=int)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [46]:
#create a numpy from 1 to 100

In [48]:
np.arange(1,101,1)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [49]:
np.arange(1,101,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [50]:
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [51]:
# rope 1 to 10 m
#5 parts 
#cut
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [55]:
np.linspace(0,11,5,endpoint=False,dtype=int)

array([0, 2, 4, 6, 8])

In [64]:
#identity matrix
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [63]:
np.eye(3,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [65]:
#random numbers generate
np.random.rand(10)

array([0.15856804, 0.09777648, 0.55295691, 0.50944899, 0.59034746,
       0.00131661, 0.81374446, 0.92669776, 0.63949834, 0.08752061])

In [66]:
np.random.rand(4,4)

array([[0.9795545 , 0.46509789, 0.52444789, 0.80106089],
       [0.18171609, 0.11875476, 0.18889902, 0.08540443],
       [0.65063907, 0.1518468 , 0.41266474, 0.24587776],
       [0.20048473, 0.83070757, 0.06086826, 0.0470947 ]])

In [67]:
#random numbers to be generated in a given range
np.random.randint(1,10,5,dtype=int)

array([4, 3, 4, 6, 9])

In [70]:
np.random.randint(12,25,(3,3),dtype=int)

array([[19, 18, 24],
       [12, 16, 12],
       [23, 12, 21]])

In [71]:
#boolean array
height = np.array([140,155,160,148,157])
weight = np.array([70,80,56,75,68])

In [75]:
height[weight>75]

array([155])

In [77]:
#2nd method
index = np.where(weight>75)
height[index]

array([155])

In [78]:
#operations

In [88]:
l1 = [1,2,3,4,5]
for i in l1:
    print(i+2)

3
4
5
6
7


In [90]:
var+2

array([3, 4, 5, 6, 7])

In [93]:
var*3

array([ 3,  6,  9, 12, 15])

In [95]:
var//2

array([0, 1, 1, 2, 2], dtype=int32)

In [97]:
var1+var1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [98]:
#what are numpy arrays
#purpose of using it
#functions/methods
#how to access the numpy arrays
#operations on numpy arrays

In [99]:
#matplotlib